sudo: false
language: node_js
node_js:
- '0.12'
before_install:
- npm install -g bower
- bower install
notifications:
  email: false
env:
  global:
  - secure: GvEE4cs3OZZ1J0E17SXWQ/EPZu0/qrvS9DyNReT+GS3rceGBJMAqEs45sUai8a4Jk8PbIQLUog0cKWzDElDgUypCsfXBPkaMpMCKLXtb0Ixp3/03vVU3KvJNIvjowhUnUfcJgOyyEQjCDsFIw3ZBnGI1H7K0WzshLY504JszTaadqUVpAk3nJtHM80lNBVy0MQ+spGARY0vsWDoQNGF07cBWEiDM/vk+hyUfJ7OHU0KTtmdTNqklDKkXQIYO7qjgb9W5NLaV4aJLTfvP/Z9wj55KWRMQBCDoDrn40yk9h6zYKeqJ4DJ3MVc8EvO6c9Bd6DuYN38tICc+r2hr/I8Dg5BP1aIyjah/nFdl7dboy6bxRmc80ydGdioKQd36sV/nPCvLTI6V+9QgVisSQZR4+zXSWMssfp+NdYXlbMkVXyDae62m70zoPK2g7IGomaHKp383TK4gs1RW1B4LBDyKjx7FkZVMqI41uBJduFtG0NO7yY4XFewspT6xGAWGZWlr+e5vqIIgKZw91VblMamd0uP2+HqXM1d1aUhp3YDjglLQeOls1tgLLKtx7xx0a4W//ArcLzXghDqfDRnbAXrJmxWKs93XvcjvZCFKjPtDZGAes7iXpcwyhtxUqvV+BD7FbvKNqmGpNFpJbs65WI0NXxT/Cp3l1IGmvMXUEK1tV4A=
  - secure: CjYduHVu3JeB12QEYs90YCrHv8HKpbNR5bROXf7NFhPM+6kZHxfaRLlJdxgpROUZfq4w9zFoR7YzZ0g9iqW3TDLyQ2LOG1TMe3JMJv0I85V1AjtLG1UvtieNFX9yS8z717csAkWz2ZagdrcslYAQuyFla+WtGb21iDWrSSbsWzi5bMGxZrmMgjMytZ2peBwDlHFHLHVrEkafao8a9ErzkaBV8Ny8l81VEGzPBGzEPGi5jrSYCrO5QFZ3kEgsew9Ep9936S3shs7XOBau5o6vNghsBIVQNl775j5SNqGB2UrtUDv5NtP/9G6jolIy+UY+HJ8KGasN/BvE2R21JhNi+dCbXwRKbvCKV/4AQnfK1TOZl+wH2/9pl7cWn04GrN3qCUzPZ3CClYE3YNDd5wW7IM4LpkUnMt1G0pvB0T+y7wyCFPwidSWUGLb93FPyCyfSComT8Qa1XKSArAzjQJgZI0mmM3LOseuGsW7M6WpfnXzAkj925A/YQv0m4AKU++pBwklLFTnK5hdL/rM25sbp3C1mwGCVl5cqBFSd+wXT1EAfDEkGNt6TJo59RwWXx/rPojEKDKlqGIGr0KH3DJ2xb8arCcAD3gLE5e1v0f6aS3H9Y6FYJkI3Mxwwmm3/60Ts844w6lT477rKhic6wwIFea0Uhz8xHMDjKb0Iyi8HR4U=
